# Makefile.deps created Tue Mar  1 03:49:37 PST 2016
debug.o: debug.c debug.h yyextern.h
stack.o: stack.c stack.h bigint.h debug.h
bigint.o: bigint.c bigint.h debug.h
token.o: token.c token.h debug.h
main.o: main.c bigint.h debug.h stack.h token.h yyextern.h
